# Generated by Django 4.2.16 on 2024-11-05 22:41

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0007_remove_animal_porte_remove_animal_raca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('mensagem', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='animal',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='detalhes_medicos',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='foto_animal',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='sexo',
        ),
        migrations.AddField(
            model_name='animal',
            name='cuidados',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('VACINADO', 'Vacinado'), ('VERMIFUGADO', 'Vermifugado'), ('CASTRADO', 'Castrado')], default=[], max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='gênero',
            field=models.CharField(choices=[('Gato', 'Gato'), ('Gata', 'Gata')], default='Gato', max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos_gatos/'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('Disponível', 'disponível'), ('Adotado', 'adotado')], default='Disponível', max_length=10),
        ),
    ]
